# Generated by Django 4.0.5 on 2022-06-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='None', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
